# 6章
## エラー処理
---
1964年のPL/Iまでに「失敗したときの処理を登録できる」「新しい失敗の種類を追加できる」「失敗を発生させられる」などの今の例外処理でも重要な要素となるいろいろな特徴が発明されてきた。

### 失敗しそうな処理を囲む
---
try/catchで囲む例外処理の公文がどうやって生まれ発展したのか
→プログラマは「命令が例外を投げる可能性があることを忘れる」「適切でない場所、または適切でない種類の例外処理を書く」などの失敗をする可能性がある。この可能性を減らし、プログラマがした失敗をコンパイラが警告できるようにするには2つのものが必要。
- 命令がどういう例外を投げる可能性があるかを明示的に宣言されること
- 字句的に「失敗しそうな処理を囲む構文」が必要である。

これによって
失敗しそうな処理を囲って書いて、エラー処理をその後に書くという構文の元になった。

### 出口を１つにする
---
プログラムが予期せず終了した場合にメモリブロックやファイルなどのリソースを正しく閉じることができるようになる。
- メモリを確保してあとで解放する
- ファイルを開いて後で閉じる
- ロックを掛けて後で外す

これを実現するための方法として
- finalllyを使う
- finallyを使わないC++のようなコンストラクタ・ディストラクタの応用
  - けどこれは、「開いたら閉じる」のような密接に関連した処理は、コードの上でも近い位置にまとまっていたほうがわかりやすいのではないかということで、例えばD言語などはスコープガードという概念を導入した。

### どういう時に例外を投げるか
---
エラーが起きたときにそれを伝える方法には2つ方法があって、
- 返り値で返す
- 例外を投げる

の2種類がある。

例外的な状況とは
- 関数呼び出し時に引数が不足している場合
  - pythonとRubyは関数呼び出し時にエラー、 jsはundefinedが返る
- 配列の範囲外の値を取得しようとしたとき
  - pythonではエラー、Rubyではnil、jsはundefined

**間違えたらすぐに例外を投げてほしい！**
フェイルファーストという概念。
「おかしくなったらすぐに処理を停止して、速やかに報告すべき」という思想が「フェイルファースト」。

### 例外の伝播
Javaを含め多くの例外処理においては、例外が呼び出し元に伝播します。
ある関数fが関数gを呼び、関数gが関数hを呼んだとする。ここで関数hの中で例外が起こると、関数hの中でその例外が処理できなかったときに、次は関数gの中で処理できるかどうか調べられる。関数gでも処理ができなかった場合は、関数fで処理できるかどうか調べられる。どの関数でも処理できなければプログラムが異常終了します。

当たり前かと思うが、これは議論の余地がある。
なぜならば、関数fのソースを見ても、関数fがどんな例外を投げるかわからないから。関数fから呼ばれる全てのソースを見なければわからない。

よってJavaでは、**検査例外**を導入している。これにより、どういう例外を投げるかを明示的に宣言することである。
Javaの例外には以下のような分類がある
- 例外処理すべきではない重大な問題
- 例外処理をしても良い、実行時例外
- 例外処理をしても良い、それ以外の例外
- その他の例外（検査例外）
  - このために用意されているのが**throws節**

### まとめ
失敗を伝える方法は大きく分けて２通り。
- 返り値で伝える
- 失敗したらジャンプする

そして
- 返り値で伝える
  - デメリット
    - 返り値をチェックし忘れ、失敗を見落としてしまう。そこで失敗したらジャンプする方法が研究されてきた。この結果、JavaやPython、Rubyなどで多くサポートされている**例外処理**の仕組みです。

例外処理にも問題がある。
１つは函数の出口が１つでなくなることによって、対にしなければならない処理を正しく対にすることが難しくなる。

